#!/usr/bin/env bash
# =============================================================================
# Create GCS bucket for Terraform remote state
# =============================================================================
# Usage:
#   ./terraform/bootstrap/setup_remote_state.sh <PROJECT_ID> [BUCKET_NAME] [REGION]
#
# Examples:
#   ./terraform/bootstrap/setup_remote_state.sh my-project
#   ./terraform/bootstrap/setup_remote_state.sh my-project my-project-tfstate us-central1
# =============================================================================

set -euo pipefail

PROJECT_ID="${1:-}"
BUCKET_NAME="${2:-}"
ENVIRONMENT="${3:-dev}"
REGION="${3:-us-central1}"
STATE_PREFIX="${STATE_PREFIX:-sap-agent/dev}"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

if [[ -z "${PROJECT_ID}" ]]; then
  log_error "Usage: $0 <PROJECT_ID> [BUCKET_NAME] [REGION]"
  exit 1
fi

if [[ -z "${BUCKET_NAME}" ]]; then
  BUCKET_NAME="${PROJECT_ID}-tfstate"
fi

if ! command -v gcloud >/dev/null 2>&1; then
  log_error "gcloud CLI is required."
  exit 1
fi

log_info "Project: ${PROJECT_ID}"
log_info "Bucket:  gs://${BUCKET_NAME}"
log_info "Region:  ${REGION}"

gcloud config set project "${PROJECT_ID}" >/dev/null

log_info "Enabling storage.googleapis.com..."
gcloud services enable storage.googleapis.com --project="${PROJECT_ID}" --quiet

if gcloud storage buckets describe "gs://${BUCKET_NAME}" --project="${PROJECT_ID}" >/dev/null 2>&1; then
  log_warn "Bucket gs://${BUCKET_NAME} already exists."
else
  log_info "Creating state bucket..."
  gcloud storage buckets create "gs://${BUCKET_NAME}" \
    --project="${PROJECT_ID}" \
    --location="${REGION}" \
    --uniform-bucket-level-access \
    --public-access-prevention
  log_success "Bucket created."
fi

log_info "Enabling versioning on state bucket..."
gcloud storage buckets update "gs://${BUCKET_NAME}" --versioning

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cp -r "${SCRIPT_DIR}/../environments/example" "${SCRIPT_DIR}/../environments/${ENVIRONMENT}"

BACKEND_FILE="${SCRIPT_DIR}/../environments/${ENVIRONMENT}/backend.gcs.tfbackend"
mkdir -p "$(dirname "${BACKEND_FILE}")"

cat > "${BACKEND_FILE}" <<EOF
# Generated by setup_remote_state.sh — do not commit if it contains project-specific values
bucket = "${BUCKET_NAME}"
prefix = "${STATE_PREFIX}"
EOF


log_success "Wrote backend config: ${BACKEND_FILE}"
echo ""
echo "Next steps:"
echo "  1. Grant your Terraform identity Storage Object Admin on gs://${BUCKET_NAME}"
echo "  2. cd terraform/environments/example"
echo "  3. cp terraform.tfvars.example terraform.tfvars  # edit project_id"
echo "  4. terraform init -backend-config=backend.gcs.tfbackend"
echo "  5. terraform plan && terraform apply"
echo ""
echo "For another project/environment, copy environments/example and set a unique prefix:"
echo "  prefix = \"sap-agent/<env>/<project>\""
echo ""
